### ISSUE TITLE
Transform credential before returning to UI

### ISSUE THREAD

**Issue by kc1116** [digitalbazaar/bedrock-credentials-rest#11]
Essentially a user should be able to specify if they want the credential to be compacted for example. Thus compaction does not have to happen in the UI. 

Heres some example code I tried to implement inside this module to no avail. 

```js
/**
 * Performs a JSON-LD transform on credential before returning it.
 *
 * @param credential the native credential to convert.
 * @param option the credential meta data.
 * @param contextURI the context to use during transform
 */
function _ldTransform(credential, option, contextURI) {
    switch(option.toLowerCase()) {
      case 'compact':
        if(contextURI){
          return jsonld.promises.compact(credential, contextURI);
        }
        return new Promise((resolve, reject) => {
          resolve(credential);
        });
      case 'normalize': 
        return jsonld.promises.normalize(credential, {format: 'application/nquads'});
      case 'flatten': 
        return jsonld.promises.flatten(credential);
      case 'expand': 
        return jsonld.promises.expand(credential);
      default:
        return new Promise((resolve, reject) => {
          resolve(credential);
        });
    }
}
```
a request looks like 'folio.com/credentials?id=nicecredential&option=compact&context=w3.org/nicecontext'

or 'folio.com/credentials?id=nicecredential&option=flatten'

@dlongley @mattcollier

**Comment by dlongley** [comment]
Having the backend do custom (client-driven) JSON-LD transformations is a potential security (e.g. DoS) risk. JSON-LD transformations should be done on the client -- and they should be very fast. If there's a performance issue, it's likely for another reason that could potentially be solved via caching or prefetching contexts that are sent to the client along with the application, etc.
