### ISSUE TITLE
Simplify the handler for getting credentials

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-credentials-rest#8]
This function should be streamlined or eliminated: https://github.com/digitalbazaar/bedrock-credentials-rest/blob/master/lib/services.credentials.js#L237

**Comment by dlongley** [comment]
Should be eliminated and its use should be replaced with effectively the same thing as what's going on here:

https://github.com/digitalbazaar/bedrock-credentials-rest/blob/master/lib/services.credentials.js#L143-L169
